"""empty message

Revision ID: 97a71b51b7b0
Revises: 63f292816cd8
Create Date: 2021-08-14 10:36:46.622625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97a71b51b7b0'
down_revision = '63f292816cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_username'), 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_username'), 'users', type_='unique')
    # ### end Alembic commands ###
